data:
  model_format: yolov7
  dataset_location: data
model:
  model_filepath: models/yolov7.pt
  trained_weights: models/runs/train/exp/weights/best.pt # Path to weights file default weights are for nano model
  data_yaml: /data.yaml
  img_size: 640 # default image size
  conf_threshold: 0.45 # confidence threshold for inference.
  iou_threshold: 0.45 # NMS IoU threshold for inference.
  device: 'cpu'  # device to run our model i.e. 0 or 0,1,2,3 or cpu
  classes: classes_to_filter  # list of classes to filter or None
predict:
  video_path: data/P1033666.mp4
  image_output_path: data/result/predicted.jpg